// Generated by CoffeeScript 1.3.3

/*
Strip email to keep only the actual reply
code inspired from this thread
http://stackoverflow.com/questions/278788/parse-email-content-from-quoted-reply
*/


(function() {

  RegExp.escape = function(text) {
    return text.replace(/[-[\]{}()*+?.,\\^$|#\s]/g, "\\$&");
  };

  /*
  sender: sender email
  text  : text body
  */


  module.exports = function(sender, text) {
    var email, index, m, reg, regexps, _i, _len;
    email = RegExp.escape(sender);
    text = text.replace(/^>.*$/gm, '');
    regexps = [RegExp("From:\\s*" + email, "gi"), RegExp("<" + email + ">", "gi"), /On.*\s*.*wrote:/gi, /-+original\s+message-+/gi, /\s+Sent\s+from\s+my.*/gi, RegExp("\\n.*" + 'ABOVE THIS LINE', "gi"), /--\n.*/gi];
    index = text.length;
    for (_i = 0, _len = regexps.length; _i < _len; _i++) {
      reg = regexps[_i];
      m = reg.exec(text);
      if (m && index > m.index) {
        index = m.index;
      }
    }
    return text.slice(0, index).trim();
  };

}).call(this);
