// Generated by CoffeeScript 1.3.3

/*
Strip email to keep only the actual reply
text: text body
*/


(function() {

  module.exports = function(text) {
    var emailReg, exp, index, m;
    text = text.replace(/^>.*$/gm, '');
    emailReg = '[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}';
    exp = RegExp("From:\\s*" + emailReg + "|<" + emailReg + ">|On.*\\s*.*wrote:|Le.*\\s*.*" + 'a écrit :' + "|-+original\\s+message-+|\\s+Sent\\s+from\\s+my.*|\\s+envoyé\\s+depuis\\s+mon.*|\\s+envoyé\\s+de\\s+mon.*|\\n.*" + 'reply above this line' + "|--\\n.*", "gi");
    m = exp.exec(text);
    index = m ? m.index : text.length;
    return text.slice(0, index).trim();
  };

}).call(this);
